# Generated by Django 2.2.7 on 2021-04-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210410_1844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
