# Generated by Django 2.2.7 on 2021-04-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='category',
            field=models.TextField(blank=True),
        ),
    ]
