# Generated by Django 2.2.7 on 2021-04-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_poster_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='category',
            field=models.CharField(choices=[('vintage', 'Vintages'), ('modern', 'Moderns'), ('classic', 'Classics')], max_length=100),
        ),
    ]
