# Generated by Django 2.2.7 on 2021-04-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210415_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile_number',
        ),
        migrations.AlterField(
            model_name='poster',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='time_stamp',
            field=models.DateTimeField(verbose_name='time'),
        ),
    ]
