# Generated by Django 2.2.7 on 2021-04-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20210426_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='category',
            field=models.CharField(choices=[('V', 'Vintage'), ('M', 'Modern'), ('C', 'Classic')], max_length=100),
        ),
    ]
