# Generated by Django 2.2.7 on 2021-04-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20210426_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='category',
            field=models.CharField(choices=[('vintage', 'Vintages'), ('modern', 'Moderns'), ('classic', 'Classics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
