# Generated by Django 2.2.7 on 2021-04-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_profile_fav_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Thrillers', 'Thriller')], max_length=100),
        ),
    ]
