# Generated by Django 2.2.7 on 2021-04-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20210427_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='price',
            new_name='actual_price',
        ),
        migrations.AddField(
            model_name='poster',
            name='discounted_price',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
