# Generated by Django 2.2.7 on 2021-04-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20210427_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='category',
            field=models.CharField(choices=[('Vintage', 'Vintages'), ('Modern', 'Moderns'), ('Classic', 'Classics')], max_length=100),
        ),
    ]
