# Generated by Django 2.2.7 on 2021-04-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=40)),
                ('email_address', models.CharField(max_length=45)),
                ('profile_image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
