# Generated by Django 2.2.7 on 2021-04-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0004_statusmessage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusmessage',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='StatusMessage',
        ),
    ]
