# Generated by Django 2.2.7 on 2021-04-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0006_auto_20210406_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusmessage',
            name='profile',
        ),
    ]
