# Generated by Django 2.2.7 on 2021-04-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0011_auto_20210407_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='mini_fb.Profile'),
        ),
    ]
